# 데이터 로드 및 사전처리
## 2. NumPy 데이터 로드
#### 참고사이트 : https://www.tensorflow.org/tutorials/load_data/numpy?hl=ko

In [2]:
import numpy as np
import tensorflow as tf

In [3]:
# .npz 파일 불러오기
DATA_URL = 'https://storage.googleapis.com/tensorflow/tf-keras-datasets/mnist.npz'

path = tf.keras.utils.get_file('mnist.npz', DATA_URL)
with np.load(path) as data:
  train_examples = data['x_train']
  train_labels = data['y_train']
  test_examples = data['x_test']
  test_labels = data['y_test']

In [4]:
# tf.data.Dataset를 사용하여 NumPy 배열을 dataset으로 변환하기
train_dataset = tf.data.Dataset.from_tensor_slices((train_examples, train_labels))
test_dataset = tf.data.Dataset.from_tensor_slices((test_examples, test_labels))

In [9]:
print(train_examples, train_labels)
print(test_examples, test_labels)
print(train_dataset)
print(test_dataset)

[[[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 ...

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]] [5 0 4 ... 5 6 8]
[[[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0

In [10]:
# dataset suffle 및 batch(집단, 무리)
BATCH_SIZE = 64
SHUFFLE_BUFFER_SIZE = 100

train_dataset = train_dataset.shuffle(SHUFFLE_BUFFER_SIZE).batch(BATCH_SIZE)
test_dataset = test_dataset.batch(BATCH_SIZE)

In [11]:
# 모델 생성 및 교육(훈련)
model = tf.keras.Sequential([
    tf.keras.layers.Flatten(input_shape=(28, 28)),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dense(10)
])

model.compile(optimizer=tf.keras.optimizers.RMSprop(),
              loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
              metrics=['sparse_categorical_accuracy'])

In [12]:
model.fit(train_dataset, epochs=10)

Epoch 1/10
938/938 [==============================] - 4s 4ms/step - loss: 3.1739 - sparse_categorical_accuracy: 0.8695
Epoch 2/10
938/938 [==============================] - 2s 3ms/step - loss: 0.4825 - sparse_categorical_accuracy: 0.9260
Epoch 3/10
938/938 [==============================] - 2s 3ms/step - loss: 0.3762 - sparse_categorical_accuracy: 0.9430
Epoch 4/10
938/938 [==============================] - 2s 2ms/step - loss: 0.3084 - sparse_categorical_accuracy: 0.9538
Epoch 5/10
938/938 [==============================] - 2s 2ms/step - loss: 0.2843 - sparse_categorical_accuracy: 0.9582
Epoch 6/10
938/938 [==============================] - 2s 2ms/step - loss: 0.2529 - sparse_categorical_accuracy: 0.9636
Epoch 7/10
938/938 [==============================] - 2s 2ms/step - loss: 0.2348 - sparse_categorical_accuracy: 0.9668
Epoch 8/10
938/938 [==============================] - 2s 2ms/step - loss: 0.2312 - sparse_categorical_accuracy: 0.9693
Epoch 9/10
938/938 [============================

In [13]:
model.evaluate(test_dataset)

157/157 [==============================] - 0s 2ms/step - loss: 0.7637 - sparse_categorical_accuracy: 0.9502


[0.7637148248311969, 0.9502]